.core-defs:
  variables:
    CORENAME: agon
    GIT_SUBMODULE_STRATEGY: recursive

.rust-target-install:
  before_script:
    - rustup target add ${RUST_TARGET}

include:
  - project: 'libretro-infrastructure/ci-templates'
    file: '/rust-windows-x64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/rust-linux-x64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/rust-apple.yml'

stages:
  - build-prepare
  - build-shared
  - build-static

libretro-build-windows-x64:
  extends:
    - .libretro-rust-windows-x64-default
    - .core-defs
    - .rust-target-install
  variables:
    RUST_TARGET: x86_64-pc-windows-gnu

libretro-build-linux-x64:
  extends:
    - .libretro-rust-linux-x64-default
    - .core-defs
    - .rust-target-install
  variables:
    RUST_TARGET: x86_64-unknown-linux-gnu

libretro-build-linux-aarch64:
  extends:
    - .libretro-rust-linux-x64
    - .core-defs
  variables:
    RUST_TARGET: aarch64-unknown-linux-gnu
    TARGET_ARCH: aarch64-unknown-linux-gnu
    CC: aarch64-linux-gnu-gcc
    CXX: aarch64-linux-gnu-g++
    AR: aarch64-linux-gnu-ar
    STRIP: aarch64-linux-gnu-strip
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
  before_script:
    - apt-get update -qy && apt-get install -yq g++-aarch64-linux-gnu
    - rustup target add ${RUST_TARGET}

libretro-build-linux-thumb2:
  extends:
    - .libretro-rust-linux-x64
    - .core-defs
  variables:
    RUST_TARGET: thumbv7neon-unknown-linux-gnueabihf
    TARGET_ARCH: thumbv7neon-unknown-linux-gnueabihf
    CC: arm-linux-gnueabihf-gcc
    CXX: arm-linux-gnueabihf-g++
    AR: arm-linux-gnueabihf-ar
    STRIP: arm-linux-gnueabihf-strip
    CARGO_TARGET_THUMBV7NEON_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
  before_script:
    - apt-get update -qy && apt-get install -yq g++-arm-linux-gnueabihf
    - rustup target add ${RUST_TARGET}

libretro-build-osx-x64:
  extends:
    - .libretro-rust-osx-x86_64-default
    - .core-defs
  variables:
    RUST_TARGET: x86_64-apple-darwin
  before_script:
    - !reference [.libretro-rust-osx-x86_64-default, before_script]
    - rustup target add ${RUST_TARGET}

libretro-build-osx-arm64:
  extends:
    - .libretro-rust-osx-arm64-default
    - .core-defs
  variables:
    RUST_TARGET: aarch64-apple-darwin
  before_script:
    - !reference [.libretro-rust-osx-arm64-default, before_script]
    - rustup target add ${RUST_TARGET}
